# Generated by Django 4.2 on 2023-10-01 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticuloDeportivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("deporte", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Univalluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("TI", "Tarjeta de Identidad"),
                        ],
                        max_length=2,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=20)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                (
                    "codigo_estudiante",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("correo_electronico", models.EmailField(max_length=254, unique=True)),
                (
                    "tipo_univalluno",
                    models.CharField(
                        choices=[
                            ("Estudiante", "Estudiante"),
                            ("Funcionario", "Funcionario"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "unique_together": {("tipo_documento", "numero_documento")},
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora_prestamo", models.DateTimeField(auto_now_add=True)),
                ("fecha_hora_vencimiento", models.DateTimeField()),
                ("devuelto", models.BooleanField(default=False)),
                (
                    "articulo_deportivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.articulodeportivo",
                    ),
                ),
                (
                    "univalluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.univalluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora_generacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_hora_pago", models.DateTimeField(blank=True, null=True)),
                ("monto", models.IntegerField(blank=True, null=True)),
                ("multa_pagada", models.BooleanField(default=False)),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.prestamo"
                    ),
                ),
            ],
        ),
    ]
